services:
  - type: web
    name: claude-token-alert-bot
    env: python
    region: oregon  # default region; adjust as needed
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: true
      - key: WEBHOOK_URL
        value: https://claude-token-alert-bot.onrender.com
